### ISSUE TITLE
Spawning Structures in other dimensions

### ISSUE THREAD

**Issue by JamesATeasdale** [OreCruncher/Restructured#6]
I'm struggling to find a way to disable gen for everything in your mod in dimensions other than for overworld, twilight forest etc. It's created massive pillars of dirt with a structure on top in places like the Aether dimension and void dimensions. It's especially irritating with the Repose mod installed because it makes massive amounts of dirt fall through the void and lags the client considerably.

**Comment by OreCruncher** [comment]
Which version of the mod are you using?

**Comment by JamesATeasdale** [comment]
1.0.4.1

**Comment by OreCruncher** [comment]
Right now there isn't a global way to black/white list dimensions.  You would have to edit the schematics.cfg file and set the dimension information per schematic.  The default is to black list The Nether and The End - you would have to add the Aether dimension if you want to block generation in that dimension.

As for pillaring, that shouldn't be happening.  It could be the world provider is reporting "ground level" in some strange way.  Does this only happen in the Aether dimension?

I am not sure what you are referring to as the void dimension.  There is The End, and that should be black listed as a default.

**Comment by JamesATeasdale** [comment]
It happens in dimensions similar to The End and the Aether dimension such as the Compact Storage dimension.

Sorry I could have been more specific with void dimensions but it's stuff like a simple platform in the middle of absolutely nowhere. You can make one in RFtools if you want somewhere safe to build stuff or in Extra Utilities' Last Millenia dimension. 

There's usually 5+ structures within viewing distance. I'm not sure if that's normal but it was pretty cool seeing how much your mod adds.

**Comment by OreCruncher** [comment]
Gottcha.  So it seems the best course is to have a global white/blacklist of dimensions that Restructured generates in.  By default it would be a white list containing Overworld (dim 0), and the server owner/player/modpack author would have to add additional dimensions for other mods.

**Comment by OreCruncher** [comment]
Pushed update to CurseForge that allows configuring global dimension white/black list: http://minecraft.curseforge.com/projects/restructured/files
