### ISSUE TITLE
1.8.9-Crash w/ Biomes O' Plenty

### ISSUE THREAD

**Issue by WenXin20** [OreCruncher/Restructured#8]
Crash Log:
(https://github.com/OreCruncher/Restructured/files/121102/crash-2016-02-07_22.35.32-server.txt)

**Comment by OreCruncher** [comment]
Did you modify any of the village generation parameters in the configuration file?  Setting them to values Minecraft doesn't like could result in a crash like you are seeing.  More information [here](https://github.com/OreCruncher/Restructured/wiki/Village-Generation).

**Comment by WenXin20** [comment]
I see, that's probably it, although the config for those values say that the Minecraft default is zero for some reason.

**Comment by OreCruncher** [comment]
Having 0's in the restructured config essentially tells the mod to leave the settings alone and use whatever Minecraft is currently using.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by OreCruncher** [comment]
Np.  Those settings are kinda touchy if you get them too small or close.

**Comment by WenXin20** [comment]
K, thanks. :)

**Comment by OreCruncher** [comment]
@WenXin20 Did you find a set of configuration settings that work for you?  If so I can close this issue out.

**Comment by WenXin20** [comment]
Oh, yes, it works now, thanks :)

**Comment by OreCruncher** [comment]
Cool.
